<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Import Details') ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label">
                    <label><b><?php echo __('Imported') ?></b></label>
                </td>
                <td class="value">
                    <?php echo Mage::helper('core')->formatDate($this->getImport()->getCreated(), 'full', TRUE); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Type') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getImport()->getType(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Message ID') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getImport()->getMessageId(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Entity') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getImport()->getEntity(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Successes') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getImport()->getSuccesses(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Duplicates') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getImport()->getDuplicates(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Failures') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getImport()->getFailures(); ?>
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Import Lines') ?></h4>
    </div>
    <div class="fieldset">
        <?php echo $this->getChildHtml('lines'); ?>
    </div>
</div>

<?php echo $this->getChildHtml('xml'); ?>

<?php if ($this->getImport()->getEntity() == 'Inventory'): ?>
<div class="entry-edit" style="margin-top: 20px;">
    <div class="entry-edit-head">
        <h4 class="icon-head head-payment-method">Additional Information</h4>
    </div>
    <fieldset>
        <p>
            <strong>Units Received</strong><br />
            The 'available stock' figure received from OrderFlow.
        </p>
        <p>
            <strong>Units Adjusted (Quotes)</strong><br />
            The quantity required for active quotes for orders not yet submitted.
        </p>
        <p>
            <strong>Units Adjusted (Queued)</strong><br />
            The quantity required by orders not yet exported to OrderFlow.
        </p>
        <p>How the values in the columns above are used to determine the 'Updated Stock Qty' will be determined by the settings in 'Inventory Import' section of the module configuration.</p>
    </fieldset>
</div>
<?php endif; ?>