<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Request Details') ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label">
                    <label><b><?php echo __('Received') ?></b></label>
                </td>
                <td class="value">
                    <?php echo Mage::helper('core')->formatDate($this->getOrderflowRequest()->getCreated(), 'full', TRUE); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Type') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getOrderflowRequest()->getType(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Message ID') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getOrderflowRequest()->getMessageId(); ?>
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Request Lines') ?></h4>
    </div>
    <div class="fieldset">
        <?php echo $this->getChildHtml('lines'); ?>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Request Body') ?></h4>
    </div>
    <div style="word-wrap: break-word;" class="fieldset">
        <pre><?php echo htmlentities($this->getOrderflowRequest()->getRequestBody()); ?></pre>
    </div>
</div>