<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Export Details') ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label">
                    <label><b><?php echo __('Exported') ?></b></label>
                </td>
                <td class="value">
                    <?php echo Mage::helper('core')->formatDate($this->getExport()->getCreated(), 'full', TRUE); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Type') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getExport()->getType(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Entity') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getExport()->getEntity(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Successes') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getExport()->getSuccesses(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Duplicates') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getExport()->getDuplicates(); ?>
                </td>
            </tr>
            <tr>
                <td class="label">
                    <label><b><?php echo __('Failures') ?></b></label>
                </td>
                <td class="value">
                    <?php echo $this->getExport()->getFailures(); ?>
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Export Lines') ?></h4>
    </div>
    <div class="fieldset">
        <?php echo $this->getChildHtml('lines'); ?>
    </div>
</div>

<?php echo $this->getChildHtml('xml'); ?>