<div class="orderflow-config-header">
    <h4>
        <?php echo $this->__('<strong style="color:#EA7601;">OrderFlow v%s ', $this->getOrderFlowVersion())?>
    </h4>
    <p>
        <?php echo $this->__('A module provided for Realtime Despatch by the Magento agency <a target="_blank" href="%s"><strong>SixBySix</strong></a>', 'http://www.sixbysix.co.uk'); ?>.
    </p>
	<!--
    <p>
        <?php echo $this->__("Need assistance? <a target=\"_blank\" href=\"https://realtime-despatch-magento-module.codebasehq.com\">Submit a ticket</a>"); ?>
    </p>
    -->
    <p>
        <?php echo $this->__("If you have feedback, need assistance or would like to use this module, please send us an <a target=\"_blank\" href=\"mailto:enquiries@realtimedespatch.co.uk\">email</a>"); ?>.
    </p>
</div>