<div class="orderflow-config-header">
    <h4>
        <?php echo $this->__('<strong style="color:#EA7601;">OrderFlow v%s ', $this->getOrderFlowVersion())?>
    </h4>
    <p>
        <?php echo $this->__('A module provided for Realtime Despatch by the Magento agency <a target="_blank" href="%s"><strong>SixBySix</strong></a>', 'http://www.sixbysix.co.uk'); ?>.
    </p>
    <p>
        <?php echo $this->__("Support for this module is provided to OrderFlow customers thorough the usual support process, if you are an existing OrderFlow customer and you require assistance with the module please create a ticket in the <a target=\"_blank\" href=\"https://support.realtimedespatch.co.uk\">support portal</a>"); ?>.
    </p>
</div>